repos:
  - repo: https://github.com/PyCQA/flake8.git
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8
        args:
          - --max-line-length=88
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: mypy
        args: [--ignore-missing-imports, --disable-error-code=union-attr, --disable-error-code=override,
               --disable-error-code=attr-defined]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        name: isort
        args:
          - '--profile'
          - 'black'
          - '--skip-glob'
          - '**/migrations/*'
          - '--skip-glob'
          - '**/__init__.py'
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black
        args: ['--line-length', '88']
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.4
    hooks:
      - id: pylint
        name: pylint
        args:
          - '--max-line-length=88'
          - '--disable=import-error,missing-module-docstring,missing-class-docstring,missing-function-docstring,
          inconsistent-return-statements,too-few-public-methods,invalid-name,unused-argument,duplicate-code,
          wrong-import-position,wrong-import-order,logging-fstring-interpolation,cyclic-import,no-member,broad-except,
          fixme,possibly-used-before-assignment,attribute-defined-outside-init,unnecessary-lambda,raise-missing-from,
          invalid-overridden-method,protected-access,too-many-instance-attributes,arguments-differ'