version: '3.8'

services:
  fastapi:
    build: .
    command: /app/entrypoint.sh
    env_file:
      - .env
    depends_on:
      - redis
      - db
    ports:
      - "8001:8001"
    restart: always
    container_name: fastapi
    volumes:
      - ./src:/app/src
    networks:
      - service_network
    environment:
      - PYTHONPATH=/app/src

  redis:
    image: redis:7.4.2
    ports:
      - "6380:6379"
    container_name: redis_fastapi
    networks:
      service_network:
        aliases:
          - redis_fastapi
    profiles:
      - celery_auth

  celery_auth:
    build: .
    command: /app/entrypoint-celery.sh
    env_file:
      - .env
    depends_on:
      - db
      - redis
    container_name: celery_auth
    profiles:
      - celery_auth
    volumes:
      - ./src:/app/src
    networks:
      - service_network

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_CONFIG__postgres_db}
      POSTGRES_USER: ${DB_CONFIG__postgres_user}
      POSTGRES_PASSWORD: ${DB_CONFIG__postgres_password}
    ports:
      - "5433:5432"
    container_name: db
    networks:
      - service_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - service_network

  localstack:
    image: localstack/localstack:latest
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4568:4568"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    container_name: localstack_auth
    restart: always
    networks:
      - service_network

volumes:
  pgadmin:

networks:
  service_network:
    external: true
